### ISSUE TITLE
Specify path to CSS?

### ISSUE THREAD

**Issue by kaycebasques** [alik0211/gulp-inject-css#1]
How do I specify the path to the CSS? Might be helpful to include in your README.

**Comment by alik0211** [comment]
Thanks for the issue.The path to the Css file should be specified relative to the html file. I'll think about how to add this README, and if you have a suggestion, create a pull request.

**Comment by alik0211** [comment]
Thanks for the issue.

The path to the CSS file should be specified relative to the HTML file.

I'll think about how to add this README, and if you have a suggestion, create a [pull request](https://github.com/alik0211/gulp-inject-css/pulls).
