### ISSUE TITLE
Gulp 4 possible breaking change

### ISSUE THREAD

**Issue by jbellavi** [alik0211/gulp-inject-css#2]
When using Gulp 4, I run into issues where `gulp-inject-css` will search for files like `"srcindex.css"` instead of `"src/index.css"`

I had no issues prior to upgrading to Gulp 4, and I was able to fix these issues by simply changing line 40 of `gulp-inject-css`'s `index.js` to read 

       ` return '<style>\n' + fs.readFileSync(file.base + '/' + src) + '\n</style>';`
instead of 
        ` return '<style>\n' + fs.readFileSync(file.base + src) + '\n</style>';`

I am not submitting a pull request because I am not sure of the consequences of this change, and whether it is safe to change this line or not.

Am I just using gulp-inject-css wrong, or is this a result of a breaking change to gulp? Let me know if I can provide any more helpful information :)

**Comment by alik0211** [comment]
🎉 Fixed in version 0.4.0 🎉

Thank you so much for issue. Your solution works and doesn't break anything.

**Comment by jbellavi** [comment]
Yay! Thanks so much I appreciate it!! :)

Now I can fix my ugly gulpfile which was patching this each build hahaha.

**Comment by alik0211** [comment]
The difference in the versions of Gulp:

Gulp version | `cwd` (`_cwd` in v4) | `base` (`_base` in v4)
-------------  | --- | ---
3 | `C:\\works\\gulp-inject-css-test` | `C:\\works\\gulp-inject-css-test\\src\\`
4 | `C:\\works\\gulp-inject-css-test` | `C:\\works\\gulp-inject-css-test\\src`
